### PR TITLE
Create pt.json

### PR DESCRIPTION
**Pull request by appznoix**
Backend Portuguese Translation for consideration

### CODE REVIEW

**Comment by aschonfeld** [comment]
@appznoix Thanks so much for the pull request!  This is great.  Is there any chance you could also provide a similar translation to the following file: [en.json](https://github.com/man-group/dtale/blob/master/static/translations/en.json) 

The file you added strictly updates the plotly dash chart builder, the one that I linked to was for the rest of the frontend.

Once you've added that I can merge and update the controls to account for the new language support

**Comment by appznoix** [comment]
You welcome @aschonfeld. I will do it soon and let you know. Just give me a few days.

**Comment by aschonfeld** [comment]
Sounds great! Thanks

**Comment by appznoix** [comment]
Dear @aschonfeld , I finished translating and requested pulling... I guess. Looking forward.

**Review by aschonfeld — APPROVED** [review]

**Comment by aschonfeld** [comment]
@appznoix just merged.  Thanks so much for your help!

**Comment by appznoix** [comment]
You welcome. And thank you for D-Tale.

**Pull request merged**
